sample=# CREATE EXTENSION pg_stat_statements;
CREATE EXTENSION
sample=# table pg_stat_statements;
 userid | dbid  | toplevel |       queryid        |                                     query                                     | plans | total_plan_time | min_plan_time | max_plan_time | mean_plan_time | stddev_plan_time | calls |   total_exec_time   | min_exec_time | max_exec_time |   mean_exec_time    |   stddev_exec_time   | rows | shared_blks_hit | shared_blks_read | shared_blks_dirtied | shared_blks_written | local_blks_hit | local_blks_read | local_blks_dirtied | local_blks_written | temp_blks_read | temp_blks_written | blk_read_time | blk_write_time | wal_records | wal_fpi | wal_bytes
--------+-------+----------+----------------------+-------------------------------------------------------------------------------+-------+-----------------+---------------+---------------+----------------+------------------+-------+---------------------+---------------+---------------+---------------------+----------------------+------+-----------------+------------------+---------------------+---------------------+----------------+-----------------+--------------------+--------------------+----------------+-------------------+---------------+----------------+-------------+---------+-----------
     10 | 16394 | t        |  2643756286501377769 | CREATE EXTENSION pg_stat_statements                                           |     0 |               0 |             0 |             0 |              0 |                0 |     1 |             113.864 |       113.864 |       113.864 |             113.864 |                    0 |    0 |            2608 |              134 |                  53 |                   7 |              0 |               0 |                  0 |                  0 |              0 |                 0 |             0 |              0 |         521 |      42 |    249076
     10 | 16394 | f        | -3655516217747249099 | /* contrib/pg_stat_statements/pg_stat_statements--1.6--1.7.sql */            +|     0 |               0 |             0 |             0 |              0 |                0 |     1 |              0.1265 |        0.1265 |        0.1265 |              0.1265 |                    0 |    0 |              18 |                0 |                   0 |                   0 |              0 |               0 |                  0 |                  0 |              0 |                 0 |             0 |              0 |           2 |       0 |       108
        |       |          |                      |                                                                              +|       |                 |               |               |                |                  |       |                     |               |               |                     |                      |      |                 |                  |                     |                     |                |                 |                    |                    |                |                   |               |                |             |         |
        |       |          |                      | -- complain if script is sourced in psql, rather than via ALTER EXTENSION    +|       |                 |               |               |                |                  |       |                     |               |               |                     |                      |      |                 |                  |                     |                     |                |                 |                    |                    |                |                   |               |                |             |         |
        |       |          |                      |                                                                              +|       |                 |               |               |                |                  |       |                     |               |               |                     |                      |      |                 |                  |                     |                     |                |                 |                    |                    |                |                   |               |                |             |         |
        |       |          |                      |                                                                              +|       |                 |               |               |                |                  |       |                     |               |               |                     |                      |      |                 |                  |                     |                     |                |                 |                    |                    |                |                   |               |                |             |         |
        |       |          |                      | /* First we have to remove them from the extension */                        +|       |                 |               |               |                |                  |       |                     |               |               |                     |                      |      |                 |                  |                     |                     |                |                 |                    |                    |                |                   |               |                |             |         |
        |       |          |                      | ALTER EXTENSION pg_stat_statements DROP FUNCTION pg_stat_statements_reset()   |       |                 |               |               |                |                  |       |                     |               |               |                     |                      |      |                 |                  |                     |                     |                |                 |                    |                    |                |                   |               |                |             |         |
     10 | 16394 | f        | -3928201315673746786 | -- Don't want this to be available to non-superusers.                        +|     0 |               0 |             0 |             0 |              0 |                0 |     1 |              0.1096 |        0.1096 |        0.1096 |              0.1096 |                    0 |    0 |               7 |                0 |                   0 |                   0 |              0 |               0 |                  0 |    -- More  --


sample=# select pg_stat_statements_reset(0);
 pg_stat_statements_reset
--------------------------

(1 行)


sample=# table pg_stat_statements;
 userid | dbid  | toplevel |       queryid        |               query                | plans | total_plan_time | min_plan_time | max_plan_time | mean_plan_time | stddev_plan_time | calls |  total_exec_time   |   min_exec_time    |   max_exec_time    |   mean_exec_time   | stddev_exec_time | rows | shared_blks_hit | shared_blks_read | shared_blks_dirtied | shared_blks_written | local_blks_hit | local_blks_read | local_blks_dirtied | local_blks_written | temp_blks_read | temp_blks_written | blk_read_time | blk_write_time | wal_records | wal_fpi | wal_bytes
--------+-------+----------+----------------------+------------------------------------+-------+-----------------+---------------+---------------+----------------+------------------+-------+--------------------+--------------------+--------------------+--------------------+------------------+------+-----------------+------------------+---------------------+---------------------+----------------+-----------------+--------------------+--------------------+----------------+-------------------+---------------+----------------+-------------+---------+-----------
     10 | 16394 | t        | -7413994526107358253 | select pg_stat_statements_reset(0) |     0 |               0 |             0 |             0 |              0 |                0 |     1 | 1.0510000000000002 | 1.0510000000000002 | 1.0510000000000002 | 1.0510000000000002 |                0 |    1 |               0 |                0 |                   0 |                   0 |              0 |               0 |                  0 |                  0 |              0 |                 0 |             0 |              0 |           0 |       0 |         0
(1 行)

sample=# select pg_stat_statements(false);
                                                                       pg_stat_statements                               
----------------------------------------------------------------------------------------------------------------------------------------------------------------
 (10,16394,t,-7413994526107358253,,0,0,0,0,0,0,1,1.0510000000000002,1.0510000000000002,1.0510000000000002,1.0510000000000002,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
 (10,16394,t,-4324399319401280096,,0,0,0,0,0,0,1,0.7885,0.7885,0.7885,0.7885,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
(2 行)